spring:
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/demodulith
      username: root
      password: root

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

hibernate:
  transaction:
    jta:
      platform: org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform
